### ISSUE TITLE
Supporting multi-process (forked) applications

### ISSUE THREAD

**Issue by rperryng** [charlypoly/graphql-ruby-hive#9]
Hey there.

We have noticed that in our staging/production environments that usage operation is not propagating to our GraphQL Hive instance (but schema publishing works)

We're using the `graphql-ruby-hive` plugin with a `rails` server.  Locally we run the server directly with `bundle exec rails server` but in our staging/production environments we use [puma](https://github.com/puma/puma) in its [clustered (multi-process) mode](https://github.com/puma/puma/tree/f323d129bc165fdafbede8392fee94c8d03f5d66#clustered-mode).  

We also make use of puma's `preload_app!` directive.  Therefore, in staging/production our puma preloads the Rails application (including initializating the GraphQL Hive plugin), and then `fork`s this process before serving requests using one of the worker process's thread pools.

From my understanding, POSIX `fork()` [does not copy threads](https://stackoverflow.com/a/61207698), so once puma forks the process, a copy of the empty, just-intiialized `Queue` exists in the new worker processes but the thread that was spawned to consume the messages is not copied post-fork.

So with all that said, what I believe is happening is:
1. Rails app boots up
2. `GraphQL::Hive::UsageReporter` gets initialized, spins up thread to continuously read from the `Queue` structure
3. Puma forks the process (Queue is copied but the thread reading from it is not)
4. Messages get added to the `Queue` but never get read out of them
  a. [I confirmed this behaviour with a forked version of the gem with extra debugging logs](https://github.com/rperryng/graphql-ruby-hive/blob/907fc7ca83deddc3e81b710e7c39cbb3b1d47499/lib/graphql-hive/usage_reporter.rb#L30-L56)

I have also confirmed that this behaviour goes away when running our web server in a non-clustered mode.

I'm unsure of the best way to support this use-case.

Puma does offer the `on_worker_boot` callback (i.e. a post `fork` hook).  Theoretically, if `GraphQL::Hive` offered a way to control when it spawns the Queue thread, then we could use this hook to ensure the thread is created in the `fork`-ed processes.

What do you think?

Happy to implement a solution if you've got any guidance/opinions etc.

**Comment by rperryng** [comment]
For inspiration, I found this [relevant thread](https://bugs.ruby-lang.org/issues/17795) about registering hooks for when the host process is forked.

A more robust solution proposed in the thread would be to simply check [`Thread#alive?`](https://ruby-doc.org/core-2.5.0/Thread.html#method-i-alive-3F) (probably when operations are added to the buffer?) and restart it when it is dead.

**Comment by rperryng** [comment]
👋 @charlypoly is there anything else I can do to help with this?

**Comment by charlypoly** [comment]
> 👋 @charlypoly is there anything else I can do to help with this?

Hi @rperryng,

After a quick review, it seems that your proposed implementation might lead to some deadlock situations.
I plan to work on this issue soon by using puma's hooks.

**Comment by charlypoly** [comment]
Hi @rperryng,

sorry for the delay; I was working on other matters 👀 

I've conducted tests with Puma in clustered mode locally using the k6 setup present in the project and reproduced the issue (some operations were missing).
After narrowing down the issue, I realized that the issue was linked to our library hooking on `Kernel#at_exit` for clearing the buffer of operations which is not triggered in forked processes.
I came up with the following solution, which avoids losing operations, adding the following hook in your Puma config to do the job:

```rb
require 'graphql'
require 'graphql-hive'

# tell GraphQL Hive client to send operations in buffer before shutting down in clustered mode
on_worker_shutdown { |_key| GraphQL::Hive.instance&.on_exit }

```

Could you try this and let me know?
Thank you!

**Comment by rperryng** [comment]
Also FWIW, I tried out [adding a `on_start` hook to `GraphQL::Hive`](https://github.com/rperryng/graphql-ruby-hive/commit/c2989e0b776e94555c7c649d856f7a9f59b92eaa) and calling this with puma's `on_worker_boot` hook and confirmed that this also fixes the issue.

**Comment by rperryng** [comment]
@charlypoly happy new year!  Any thoughts on the above?
